# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1052, 763)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OpenBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OpenBtn.setGeometry(QtCore.QRect(20, 510, 261, 61))
        self.OpenBtn.setObjectName("OpenBtn")
        self.Imglablel = QtWidgets.QLabel(self.centralwidget)
        self.Imglablel.setGeometry(QtCore.QRect(70, 50, 771, 381))
        self.Imglablel.setObjectName("Imglablel")
        self.Infolabel = QtWidgets.QLabel(self.centralwidget)
        self.Infolabel.setGeometry(QtCore.QRect(520, 500, 391, 151))
        self.Infolabel.setObjectName("Infolabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1052, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OpenBtn.setText(_translate("MainWindow", "选择文件"))
        self.Imglablel.setText(_translate("MainWindow", "图片位置"))
        self.Infolabel.setText(_translate("MainWindow", "显示窗口"))
